version: '3.7'
services:
  spring-petclinic-angular:
    build: ./spring-petclinic-angular
    image: sch0tterfoinfoin/spring-petclinic-angular
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
    deploy:
      replicas: 1


  spring-petclinic-rest:
    build: ./spring-petclinic-rest
    image: sch0tterfoinfoin/spring-petclinic-rest
    ports:
    - target: 9966
      published: 9966
      protocol: tcp
    deploy:
      replicas: 1
  

      

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: /home/Chris/DevOps-Final/nginx/nginx.conf
      target: /etc/nginx/nginx.conf