apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: spring-petclinic-angular
  name: spring-petclinic-angular
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spring-petclinic-angular
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: spring-petclinic-angular
    spec:
      containers:
      - image: sch0tterfoinfoin/spring-petclinic-angular
        imagePullPolicy: ""
        name: spring-petclinic-angular
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
