---
dependencies: []

galaxy_info:
  role_name: jenkins
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - development
    - packaging
    - jenkins
    - ci
